version: "3"
services:
  web1:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./app1:/var/www/html
      - ./nginx1/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - mysql
    networks:
      - laravel
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app1:/var/www/html
    networks:
      - laravel
  web2:
    image: nginx:alpine
    ports:
      - "9000:9000"
    volumes:
      - ./app2:/var/www/html
      - ./nginx2/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app2
      - mysql
    networks:
      - laravel
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app2:/var/www/html
    networks:
      - laravel
  web3:
    image: nginx:alpine
    ports:
      - "7000:7000"
    volumes:
      - ./app3:/var/www/html
      - ./nginx3/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app3
      - mysql
    networks:
      - laravel
  app3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app3:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

  balancer:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./balancer/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web1
      - web2
    networks:
      - laravel
volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
